### ISSUE TITLE
Failed to build with MSVC 2013 Update 2 for x86 under Windows 7 Pro x64

### ISSUE THREAD

**Issue by gshep** [svalaskevicius/qt-event-dispatcher-libuv#10]
There is a problem with 'min/max' macros defined in some windows header. See log

```batch
Scanning dependencies of target qt-event-dispatcher-libuv_automoc
[ 12%] Automoc for target qt-event-dispatcher-libuv
Generating moc_eventdispatcherlibuv.cpp
[ 12%] Built target qt-event-dispatcher-libuv_automoc
Scanning dependencies of target qt-event-dispatcher-libuv
[ 25%] Building CXX object CMakeFiles/qt-event-dispatcher-libuv.dir/src/eventdispatcherlibuv.cpp.obj
eventdispatcherlibuv.cpp
qt-5.3-x86-msvc13\include\qtcore\qdatetime.h(122) : warning C4003: not enough actual parameters for macro 'min'
qt-5.3-x86-msvc13\include\qtcore\qdatetime.h(122) : error C2589: '(' : illegal token on right side of '::'
qt-5.3-x86-msvc13\include\qtcore\qdatetime.h(122) : error C2059: syntax error : '::'
```

**Comment by gshep** [comment]
Compilation also failed with the following errors

```batch
[ 25%] Building CXX object CMakeFiles/qt-event-dispatcher-libuv.dir/src/eventdispatcherlibuv.cpp.obj
eventdispatcherlibuv.cpp
C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(96) : warning C4005: 'AF_IPX' : macro redefinition
        C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(452) : see previous definition of 'AF_IPX'
C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(136) : warning C4005: 'AF_MAX' : macro redefinition
        C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(471) : see previous definition of 'AF_MAX'
C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(173) : warning C4005: 'SO_DONTLINGER' : macro redefinition
        C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(394) : see previous definition of 'SO_DONTLINGER'
C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(217) : error C2011: 'sockaddr' : 'struct' type redefinition
        C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(477) : see declaration of 'sockaddr'
```

Found solution here: http://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h, https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/4a90b143-1fb8-43e9-a54c-956127e0c579/windowsh-and-winsock2h?forum=windowssdk

**Comment by svalaskevicius** [comment]
Nice one! Would you be able to create a pr to share this with others?

Cheers,
Sarunas

On Wed, 28 Oct 2015 11:13 Georgy Shepelev <notifications@github.com> wrote:

> Compilation also failed with the following errors
>
> [ 25%] Building CXX object CMakeFiles/qt-event-dispatcher-libuv.dir/src/
>
> eventdispatcherlibuv.cpp.obj
> eventdispatcherlibuv.cpp
> C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(96) : warning C4005: 'AF_IPX' : macro redefinition
>         C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(452) : see previous definition of 'AF_IPX'
> C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(136) : warning C4005: 'AF_MAX' : macro redefinition
>         C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(471) : see previous definition of 'AF_MAX'
> C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(173) : warning C4005: 'SO_DONTLINGER' : macro redefinition
>         C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(394) : see previous definition of 'SO_DONTLINGER'
> C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(217) : error C2011: 'sockaddr' : 'struct' type redefinition
>         C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(477) : see declaration of 'sockaddr'
>
> Found solution here:
> http://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h,
>
> https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/4a90b143-1fb8-43e9-a54c-956127e0c579/windowsh-and-winsock2h?forum=windowssdk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/svalaskevicius/qt-event-dispatcher-libuv/issues/10#issuecomment-151805499>
> .
>
-- 
*Sarunas Valaskevicius*
Technical Team Lead, Senior Technical Consultant (Zend Certified Engineer
PHP5.3, Magento Certified Developer Plus)

*Inviqa*
enterprise open source

skype: svalaskevicius.inviqa
e-mail: svalaskevicius@inviqa.com

phone: +44 20 3179 9555
twitter: @swoq <http://twitter.com/#!/swoq> @Inviqa
<http://twitter.com/#!/Inviqa>
*inviqa.com <http://www.inviqa.com>*

Disclaimer
This email and any attachments may be confidential and are intended solely
for the use of the addressee. Any views or opinions expressed are those of
the author and may not represent those of Inviqa. If you are not the
intended recipient of this email, you must neither take any action based
upon its contents, nor copy or show it to anyone. Please contact the sender
if you believe you have received this email in error.

**Comment by svalaskevicius** [comment]
Found it, my bad :) 

Thanks again!
