### ISSUE TITLE
MIT/BSD-style license

### ISSUE THREAD

**Issue by c0nk** [svalaskevicius/qt-event-dispatcher-libuv#5]
Can you bless this code with MIT/BSD-style license? I like your work.

**Comment by svalaskevicius** [comment]
Thanks!

just curious - I thought LGPL was very permissive or is MIT/BSD still better?

if its more convenient - of course - I don't mind having either of those for this repo and will add in the readme a bit later :)

**Comment by svalaskevicius** [comment]
done - updated the readme to point to BSD license instead

**Comment by c0nk** [comment]
Perfect. Thanks!
